name: Build, Scan and Push

on:
  push:
    branches:
      - main

jobs:

  build-scan-push:

    runs-on: ubuntu-22.04

    steps:

      # ====================================
      # 1. Checkout source code
      # ====================================

      - name: Checkout source
        uses: actions/checkout@v4


      # ====================================
      # 2. Build Docker image
      # ====================================

      - name: Build Docker image
        run: |
          docker build \
            -t tmas-cicd-lab:${{ github.sha }} .


      # ====================================
      # 3. TMAS Scan
      # ====================================

      - name: TMAS Container Scan
        uses: trendmicro/tmas-scan-action@v3.1.3
        with:
          version: '2'
          vulnerabilitiesScan: true
          malwareScan: true
          secretsScan: true

          artifact: docker:tmas-cicd-lab:${{ github.sha }}

          additionalArgs: --region=ap-southeast-1

          tmasApiKey: ${{ secrets.TMAS_API_KEY }}

          githubToken: ${{ secrets.GITHUB_TOKEN }}


      # ====================================
      # 4. Login to Quay
      # ====================================

      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}


      # ====================================
      # 5. Tag image
      # ====================================

      - name: Tag image
        run: |
          docker tag \
            tmas-cicd-lab:${{ github.sha }} \
            quay.io/admin1hyperzonemii/tmas-cicd-lab:${{ github.sha }}


      # ====================================
      # 6. Push image
      # ====================================

      - name: Push image
        run: |
          docker push \
            quay.io/admin1hyperzonemii/tmas-cicd-lab:${{ github.sha }}
